name: last_bite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter 
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  pixelarticons: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo_1.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "images/logo_foreg.png"

flutter:
  uses-material-design: true
  assets:
      - images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          style: italic
    - family: Jersey
      fonts:
        - asset: fonts/Jersey20/Jersey20-Regular.ttf